import json,subprocess,urllib.parse
P=[
('headshot','Death From Front Headshot','Rifle Death From Front Headshot'),
('headshot','Death From Back Headshot','Rifle Death From Back Headshot'),
('headshot','Death Crouching Headshot Front','Rifle Death Crouched From Headshot Front'),
('headshot','Dying','Dying Shot To The Head Falling On Two Knees'),
('headshot','Dying','Dying Shot To Back Of Head Falling On Two Knees'),
('headshot','Dying','Dying Front Head Impact To Two Knees'),
('headshot','Dying','Dying With Front Hit To The Head And Fall On One Knee'),
('headshot','Dying','Dying With Front Impact To The Head And Fall On One Knee'),
('headshot','Standing React Small From Headshot','Hit Reaction From Headshot With Bow'),
('torso','Dying Backwards','Shot To The Chest Falling Backwards'),
('torso','Falling Back Death','Dying Falling Backward'),
('torso','Falling Forward Death','Dying Falling Forward'),
('torso','Standing React Death Backward','Death Falling Backwards'),
('torso','Standing React Death Forward','Death Falling Forwards'),
('torso','Standing React Death Left','Death Falling To The Left'),
('torso','Standing React Death Right','Death Falling To The Right'),
('torso','Death From The Front','Rifle Death From The Front'),
('torso','Death From The Back','Rifle Death From The Back'),
('torso','Death From Right','Rifle Death From Right Side'),
('torso','Dying','Dying Shot To The Chest Falling On Two Knees'),
('torso','Dying','Dying Rear Impact Falling On Two Knees'),
('torso','Dying','Death Hit From The Back Falling On One Knee'),
('torso','Death','Death From Standing Idle'),
('torso','Rifle Death','Dying Reaction While Standing Holding A Rifle'),
('torso','Rifle Run To Dying','Getting Shot While Running With An Aimed Rifle'),
('torso','Walking To Dying','Walking While Aiming Rifle To Dying'),
('torso','Fall Flat','Falling Flat On Face From A Hit To The Back While Running'),
('torso','Shoulder Hit And Fall','Hit In The Shoulder And Falls To The Ground'),
('torso','Standing Death Backward 01','Death Reaction Falling Backwards With Bow'),
('torso','Standing Death Forward 01','Death Reaction Falling Forwards With Bow'),
('torso','Standing Death Left 01','Death Reaction Falling Left With Bow'),
('torso','Standing Death Right 01','Death Reaction Falling Right With Bow'),
('torso','Crouch Death','Dying From A Crouched Position'),
('torso','Prone Death','Dying From A Prone Position'),
('torso','Zombie Stumbling','Zombie Stumble To The Right And Fall'),
('leg','Hit To The Legs','Hit To The Legs With Object While Running'),
('leg','Hit On Legs','Hit On Back Of Legs With An Object While Running'),
('leg','Sweep Fall','Getting Feet Swept Out From Underneath And Falling'),
('leg','Tripping','Walk To Tripping And Falling'),
('leg','Stumble Backwards','Slip And Fall Backwards'),
('leg','Injured Hurting Idle','Injured Holding Hurt Leg Idle'),
('leg','Injured Walk','Injury On Right Leg And Arm'),
('leg','Injured Stumble Idle','Injured Stumbling Idle'),
('explosion','Flying Back Death','Dying Flying Backward'),
('explosion','Dying','Explosion From Behind'),
('explosion','Getting Thrown','Being Thrown To The Side'),
('explosion','Getting Hit Backwards','Getting Hit And Flipping Backwards'),
('explosion','Hit By Car','Getting Hit By A Car While Tired'),
('explosion','Hard Landing','Mid-Air Falling To A Hard Landing'),
('explosion','Falling Flat Impact','Falling Flat On Face'),
('explosion','Jump Away','Jumping Away To Avoid Explosion'),
('knockdown','Knocked Down','Knocked Down To Stomach'),
('knockdown','Knocked Out','Knocked Out Falling To Back'),
('knockdown','Knocked Out','Knocked Out Falling To Stomach'),
('knockdown','Falling Down','Knocked Over And Falling To The Ground'),
('knockdown','Stunned','Male Knocked Down From A Punch'),
('knockdown','Livershot Knockdown','Receiving A Hit To The Liver'),
('knockdown','Swing Into Wall','Swing In Hit Wall To Crouched Land'),
('knockdown','Being Electrocuted','Being Electrocuted Into Unconciousness'),
('knockdown','Slipping','Frantically Slip And Fall To Stomach'),
('getup','Getting Up','Getting Up From Back'),
('getup','Getting Up','Getting Up From Stomach'),
('getup','Getting Up','Getting Up From Being Knocked Down On The Ground'),
('getup','Getting Up','Standing From A Lying Prone'),
('getup','Stand Up','Standing Up From Back'),
('getup','Standing Up','Standing Up From Lying On Stomach'),
('getup','Zombie Stand Up','Zombie Laying On Back To Standing Up'),
('getup','Zombie Stand Up','Zombie Laying On Stomach To Standing Up'),
('getup','Zombie Stand Up','Zombie Laying On Side To Standing Up'),
('hit_reaction','Hit Reaction','Hit Reaction'),
('hit_reaction','Hit Reaction','Hit Reaction While Holding A Rifle'),
('hit_reaction','Hit Reaction','Hit Reaction While Holding A Pistol'),
('hit_reaction','Head Hit','Receiving A Big Hit To The Head From A Straight Punch'),
('hit_reaction','Head Hit','Receiving A Light Hit To The Head From A Left Punch'),
('hit_reaction','Standing React Large From Front','Large Hit Reaction From The Front'),
('hit_reaction','Standing React Large From Back','Large Hit Reaction From The Back'),
('hit_reaction','Standing React Large From Left','Large Hit Reaction From The Left'),
('hit_reaction','Standing React Large From Right','Large Hit Reaction From The Right'),
('hit_reaction','Standing React Small From Front','Small Hit Reaction From The Front'),
('hit_reaction','Standing React Small From Back','Small Hit Reaction From The Back'),
('hit_reaction','Standing React Small From Left','Small Hit Reaction From The Left'),
('hit_reaction','Standing React Small From Right','Small Hit Reaction From The Right'),
('hit_reaction','Stomach Hit','Receiving A Hit In The Stomach'),
('hit_reaction','Big Rib Hit','Receiving A Big Hit In The Ribs'),
('hit_reaction','Reaction','Male Reaction Hit On The Left Side'),
('hit_reaction','Reaction','Male Reaction Hit On The Right Side'),
('hit_reaction','Shove Reaction','Standing Reaction To Shove'),
('hit_reaction','Shoved Reaction With Spin','Reaction To Getting Clipped While Walking Unaware'),
('hit_reaction','Jogging Stumble','Brief Stumble While Jogging'),
('hit_reaction','Zombie Reaction Hit','Zombie Reaction Hit Stumble Back'),
('hit_reaction','Walking Hit Reaction','Hit Reaction When Walking While Aiming Rifle'),
]
out=[]
for cat,name,desc in P:
    u=f"https://www.mixamo.com/api/v1/products?page=1&limit=96&type=Motion&query={urllib.parse.quote(name)}"
    r=json.loads(subprocess.run(['curl','-s','-m','30',u,'-H','X-Api-Key: mixamo2'],capture_output=True,text=True).stdout)['results']
    m=[x for x in r if x['name']==name and x['description']==desc]
    out.append(dict(name=name,duration=None,category=cat,description=desc,motion_id=m[0]['id'] if m else None))
    if not m: print('MISSING',name,desc)
json.dump(out,open('/home/user/game/assets/deaths/_tools/mixamo_pick.json','w'),indent=1)
with open('/home/user/game/assets/deaths/mixamo_death_hit_names.txt','w') as f:
    f.write('# Mixamo motions (exact product name :: description :: motion id), queried 2026-09-29 via mixamo.com/api/v1/products. Download needs a free Adobe ID; not redistributable raw.\n')
    for c in ['headshot','torso','leg','explosion','knockdown','getup','hit_reaction']:
        f.write(f'\n## {c}\n'); [f.write(f"{o['name']} :: {o['description']} :: {o['motion_id']}\n") for o in out if o['category']==c]
print(len(out))
