// Saber test: ignite, chain, heavy, block rules, dual/reverse previews.
import { chromium } from 'playwright';
const URL = process.env.URL || 'http://localhost:8766/preview2.html';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
p.on('pageerror', e => console.log('pageerror:', e.message));
p.on('console', m => { if (m.type() === 'error' && !/404|CERT/.test(m.text())) console.log('console', m.text()); });
await p.goto(URL);
await p.waitForFunction(() => window.__game, null, { timeout: 90000 });
const st = () => p.evaluate(() => ({ armed: __game.armed, atk: __game.atk, block: __game.blocking, s: +__game.speed.toFixed(1), m: __game.mode }));
await p.keyboard.press('KeyE'); await p.waitForTimeout(700);
console.log('ignited', await st()); await p.screenshot({ path: 'v5-stance.png' });
await p.keyboard.down('KeyW'); await p.waitForTimeout(1200); await p.screenshot({ path: 'v5-run-armed.png' });
await p.keyboard.down('ShiftLeft'); await p.waitForTimeout(1500); console.log('sprinting', await st());
await p.evaluate(() => { __game.attackPress(); __game.attackRelease(); }); await p.waitForTimeout(150);
console.log('attack while sprinting ->', await st()); await p.screenshot({ path: 'v5-attackA.png' });
await p.keyboard.up('ShiftLeft'); await p.keyboard.up('KeyW');
await p.evaluate(() => { __game.attackPress(); __game.attackRelease(); }); await p.waitForTimeout(500);
console.log('chain', await st()); await p.screenshot({ path: 'v5-attackB.png' });
await p.evaluate(() => { __game.attackPress(); __game.attackRelease(); }); await p.waitForTimeout(700);
console.log('chain', await st()); await p.screenshot({ path: 'v5-attackC.png' });
await p.waitForTimeout(2500); console.log('after chain', await st());
await p.evaluate(() => __game.attackPress()); await p.waitForTimeout(900); console.log('held', await st()); await p.screenshot({ path: 'v5-heavy.png' });
await p.evaluate(() => __game.attackRelease()); await p.waitForTimeout(4000);
await p.evaluate(() => __game.blockPress()); await p.keyboard.down('KeyW'); await p.keyboard.down('ShiftLeft'); await p.waitForTimeout(900);
await p.keyboard.press('Space'); await p.waitForTimeout(200);
console.log('block + sprint + jump ->', await st()); await p.screenshot({ path: 'v5-block.png' });
await p.evaluate(() => __game.blockRelease()); await p.keyboard.up('KeyW'); await p.keyboard.up('ShiftLeft'); await p.waitForTimeout(1200);
console.log('released', await st());
// Moves: dual + reverse
await p.click('#movesbtn'); await p.waitForTimeout(400);
await p.click('[data-sstyle="dual"]'); await p.click('[data-sgrip="reverse"]'); await p.click('[data-scolor="Purple"]'); await p.waitForTimeout(600);
await p.screenshot({ path: 'v5-dual-reverse.png' });
await p.click('[data-sstyle="staff"]'); await p.click('[data-sgrip="normal"]'); await p.click('[data-lib="Sword_Regular_Combo"]'); await p.waitForTimeout(900);
await p.screenshot({ path: 'v5-staff.png' });
await p.click('[data-sstyle="single"]'); await p.click('[data-scolor="Green"]');
await p.click('#movesclose'); await p.waitForTimeout(500); console.log('closed', await st());
const m = await b.newPage({ viewport: { width: 375, height: 740 }, hasTouch: true, isMobile: true });
await m.goto(URL); await m.waitForFunction(() => window.__game, null, { timeout: 90000 });
await m.tap('#saberbtn'); await m.waitForTimeout(700); await m.screenshot({ path: 'v5-mobile.png' });
await b.close();
