import { chromium } from 'playwright';
const proxy = undefined;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', proxy, args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-certificate-errors'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
p.on('console', m => console.log('console:', m.type(), m.text()));
p.on('pageerror', e => console.log('pageerror:', e.message));
await p.goto('http://localhost:8765/preview.html');
await p.waitForFunction(() => window.__game, null, { timeout: 60000 });
console.log('cal', JSON.stringify(await p.evaluate(() => window.__cal)));
await p.waitForTimeout(800);
await p.screenshot({ path: 'shot-idle.png' });
await p.keyboard.down('KeyW'); await p.waitForTimeout(1500);
console.log('jog speed', await p.evaluate(() => window.__game.speed));
await p.screenshot({ path: 'shot-jog.png' });
await p.keyboard.down('KeyD'); await p.keyboard.down('ShiftLeft'); await p.waitForTimeout(1500);
console.log('sprint speed', await p.evaluate(() => window.__game.speed));
await p.keyboard.press('Space'); await p.waitForTimeout(200);
await p.screenshot({ path: 'shot-sprint-jump.png' });
await p.keyboard.up('KeyW'); await p.keyboard.up('KeyD'); await p.keyboard.up('ShiftLeft'); await p.waitForTimeout(1200);
console.log('stopped', await p.evaluate(() => window.__game.speed));
const m = await b.newPage({ viewport: { width: 375, height: 740 }, hasTouch: true, isMobile: true });
await m.goto('http://localhost:8765/preview.html');
await m.waitForFunction(() => window.__game, null, { timeout: 60000 }); await m.waitForTimeout(800);
await m.screenshot({ path: 'shot-mobile.png' });
await b.close();
