// v31: the player's energy shield (Pistol + energy shield) and the shield soldier's one-handed stance.
import { chromium } from 'playwright';
const URL = process.env.URL || 'http://127.0.0.1:8766/preview2.html', OUT = process.env.OUT || '.';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
const errs = []; p.on('pageerror', e => { errs.push(e.message); console.log('pageerror:', e.message); });
await p.goto(URL); await p.waitForFunction(() => window.__game, null, { timeout: 120000 });
const ev = (f, a) => p.evaluate(f, a);
let fail = 0; const check = (ok, msg) => { console.log(ok ? 'ok  ' : 'FAIL', msg); if (!ok) fail++; };
const park = () => ev(() => { __game.fillEnemies(); __game.advance(0.2); const n = __game.enemies().filter((e) => e.state !== 'dead').length; for (let i = 0; i < n; i++) { __game.moveEnemy(i, 60 + i * 4, 60); __game.setMind(i, 'patrol', 999); } __game.advance(0.1); });
await ev(() => { __game.place(-3, 3); __game.look(0, 0.1); __game.advance(0.3); });
await park();
check((await ev(() => __game.countItem('shieldpistol'))) === 1, 'the energy shield is handed out once');
await ev(() => { const I = __game.inv, bi = I.bag.findIndex((x) => x && x.id === 'shieldpistol'); const t = I.hot[1]; I.hot[1] = I.bag[bi]; I.bag[bi] = t; __game.selectSlot(1); __game.advance(1.5); });
let sh = await ev(() => __game.shield());
check(sh.up && sh.visible, 'selecting it draws the pistol with the shield on your left arm');
const hand = await ev(() => { const q = __game.boneQ(); return true; });
await ev(() => { __game.moveEnemy(0, -3, -6, 0); __game.setMind(0, 'combat', 0); __game.advance(0.2); __game.enemyBolt(0); __game.advance(1.2); });
sh = await ev(() => __game.shield());
check(sh.blocked >= 1 && sh.hp < 1, `a bolt from the front hits the shield (blocked ${sh.blocked}, charge ${sh.hp})`);
await p.screenshot({ path: `${OUT}/v31-shield.png` });
const before = sh.blocked;
await ev(() => { __game.moveEnemy(0, -3, 12, Math.PI); __game.advance(0.2); __game.enemyBolt(0); __game.advance(1.2); });
check((await ev(() => __game.shield())).blocked === before, 'a bolt from behind gets past it');
await ev(() => { __game.moveEnemy(0, -3, -6, 0); __game.advance(0.2); for (let i = 0; i < 14; i++) { __game.enemyBolt(0); __game.advance(0.35); } __game.advance(0.8); });
sh = await ev(() => __game.shield());
check(!sh.up && sh.down > 0 && !sh.visible, `enough hits drain it and it drops (back in ${sh.down} s)`);
await park(); await ev(() => __game.advance(9));
sh = await ev(() => __game.shield());
check(sh.up && sh.hp > 0.9, 'it comes back charged');
await ev(() => { __game.selectSlot(0); __game.advance(1.5); });
check(!(await ev(() => __game.shield())).visible, 'switching to the saber puts it away');
// the shield soldier holds his left forearm out in front
await park();
const j = await ev(() => __game.spawnSpecial('shield', -3, -3));
await ev((j) => { const i = __game.enemies().filter((e) => e.state !== 'dead').findIndex((e) => e.id === j); __game.setMind(i, 'combat', 0); __game.advance(1); }, j);
const hb = await ev((j) => __game.enemyBone(j, 'hand_l'), j), eb = await ev((j) => __game.enemyBone(j, 'upperarm_l'), j);
const fwd = (P) => (P.at[0] - P.g[0]) * Math.sin(P.yaw) + (P.at[2] - P.g[2]) * Math.cos(P.yaw);
check(fwd(hb) - fwd(eb) > 0.25, `the shield soldier's left hand is out in front (${(fwd(hb) - fwd(eb)).toFixed(2)} m ahead of his shoulder)`);
await ev(() => { __game.look(0, 0.05); __game.advance(0.2); });
await p.screenshot({ path: `${OUT}/v31-jackal.png` });
check(errs.length === 0, 'no page errors');
await b.close();
console.log(fail ? `FAILED (${fail})` : 'PASS'); process.exit(fail ? 1 : 0);
