import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
p.on('console', m => { if (!/GPU stall|deprecated/.test(m.text())) console.log('console:', m.type(), m.text()); });
p.on('pageerror', e => console.log('pageerror:', e.message));
await p.goto('http://localhost:8765/preview2.html');
await p.waitForFunction(() => window.__game, null, { timeout: 90000 });
console.log('cal', JSON.stringify(await p.evaluate(() => window.__cal)));
const st = () => p.evaluate(() => ({ s: +window.__game.speed.toFixed(2), m: window.__game.mode, g: window.__game.gait, j: window.__game.jumps }));
await p.evaluate(() => window.__game.setClass('force'));
await p.keyboard.down('KeyW'); await p.keyboard.down('ShiftLeft'); await p.waitForTimeout(2500);
console.log('sprint', await st()); await p.screenshot({ path: 'v2-sprint.png' });
await p.keyboard.press('KeyC'); await p.waitForTimeout(250); console.log('slide', await st()); await p.screenshot({ path: 'v2-slide.png' });
await p.waitForTimeout(1500); console.log('after slide', await st());
await p.keyboard.press('Space'); await p.waitForTimeout(250); console.log('jump', await st());
await p.keyboard.press('Space'); await p.waitForTimeout(200); console.log('djump', await st()); await p.screenshot({ path: 'v2-djump.png' });
await p.waitForTimeout(2500); console.log('landed', await st());
await p.keyboard.up('KeyW'); await p.keyboard.up('ShiftLeft'); await p.waitForTimeout(1500);
console.log('stop', await st()); await p.screenshot({ path: 'v2-idle.png' });
const m = await b.newPage({ viewport: { width: 375, height: 740 }, hasTouch: true, isMobile: true });
m.on('pageerror', e => console.log('m pageerror:', e.message));
await m.goto('http://localhost:8765/preview2.html');
await m.waitForFunction(() => window.__game, null, { timeout: 90000 }); await m.waitForTimeout(800);
await m.screenshot({ path: 'v2-mobile.png' });
await m.tap('#movesbtn'); await m.waitForTimeout(1500); await m.screenshot({ path: 'v2-moves.png' });
await m.tap('[data-slot="slide"].pv'); await m.waitForTimeout(700); await m.screenshot({ path: 'v2-moves-slide.png' });
await b.close();
